# Generated by Django 5.1.4 on 2025-01-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dob', models.CharField(max_length=255)),
                ('gstin', models.CharField(max_length=255)),
                ('firm_name', models.CharField(max_length=255)),
                ('firm_type', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('annual_turnover', models.CharField(max_length=255)),
                ('property_ownership', models.CharField(max_length=255)),
            ],
        ),
    ]
